import '../styles/globals.css';
import Head from 'next/head';
import Script from 'next/script'
import { Router, useRouter } from 'next/router';
import type { AppProps } from 'next/app';
import AppContext from '../AppContext';
import Header from '../components/Header';
import { emptyUser } from '../types';
import { useState, useEffect } from 'react';
import { checkUserToken, getLanguages } from '../helpers';
import LoginForm from '../components/LoginForm';

import Chat from '../components/Chat';
import User from '../classes/User';

const getPageTitle = (pageProps: any) => {
  const pageMeta = pageProps.pageMeta;
  return pageMeta?.title || 'Sam - Web Developer';
};

function MyApp({ Component, pageProps }: AppProps) {
  const [user, setUser] = useState(emptyUser);
  const [lang, setLang] = useState(getLanguages('en'));
  const [showLogin, setShowLogin] = useState(false);

  const [loading, setLoading] = useState(false);
  Router.events.on('routeChangeStart', () => {
    setLoading(true);
  });

  Router.events.on('routeChangeComplete', () => {
    setLoading(false);
  });

  const router = useRouter();

  useEffect(() => {
    const userResponse = checkUserToken();
    userResponse.then((res: any) => {
      if (res?.user) {
        setUser(res.user);
      }
    });
  }, []);

  useEffect(() => {
    setLang(getLanguages(router.locale));
  }, [router.locale]);

  return (
    <>
      <Head>
        <title>{getPageTitle(pageProps)}</title>
        <meta name="keywords" content="" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
        <script src="https://cdn.tailwindcss.com" async></script>
      </Head>
      <AppContext.Provider
        value={{
          user,
          lang,
          setUser,
        }}
      >
        {/* <Chat /> */}
        <main className="p-3">
          <Header
            setShowLogin={setShowLogin}
            lang={lang}
            user={user}
            setUser={setUser}
            router={router}
          />
          <section className="bg-card mt-2 p-2 rounded">
            {loading && <div>Loading...</div>}
            <Component {...pageProps} />
          </section>
          {!user._id && showLogin ? (
            <LoginForm setShowLogin={setShowLogin} setUser={setUser} />
          ) : null}
        </main>
      </AppContext.Provider>
    </>
  );
}

export default MyApp;
