import '../styles/globals.css';
import Head from 'next/head';
import Link from 'next/link';
import type { AppProps } from 'next/app';

const getPageTitle = (pageProps: any) => {
  const pageMeta = pageProps.pageMeta;
  return pageMeta?.title || 'Dashboard';
};

const NAV_LINKS = [
  { tl: 'Knowledges', url: '/knowledges' },
  { tl: 'Expense', url: '/expense' },
  { tl: 'Comments', url: '/comments' },
  { tl: 'Subscription', url: '/newsletter' },
  { tl: 'Map', url: '/map' },
];

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>{getPageTitle(pageProps)}</title>
        <meta name="keywords" content="" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
        />
        <link rel="stylesheet" href="/tailwind.css" />
      </Head>
      <main className="flex">
        <header className="w-1/4 bg-white">
          <nav className="flex flex-col p-2">
            {NAV_LINKS.map((nav) => (
              <Link key={nav.url} href={nav.url}>
                <span className="mb-3 cursor-pointer text-red-300 hover:text-red-500 transition duration-300">
                  {nav.tl}
                </span>
              </Link>
            ))}
          </nav>
        </header>
        <Component {...pageProps} />
      </main>
    </>
  );
}

export default MyApp;
