import type { GetServerSideProps, GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  useEffect(()=>{
  },[]);
  return (
    <div className={styles.container}>
      <Head>
        <title>My Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className='flex flex-wrap'>
          <article className="p-2 w-full sm:w-1/2 md:w-1/3 lg:w-1/4">
            <div className="card p-2 shadow bg-blue-400">
              <h2 className='text-2xl text-white'>Todos</h2>
              <i className="fa-solid text-white text-xl fa-list"></i>
            </div>
          </article>
          <article className="p-2 w-full sm:w-1/2 md:w-1/3 lg:w-1/4">
            <div className="card p-2 shadow bg-red-400">
              <h2 className='text-2xl text-white'>Comments</h2>
              <i className="fa-solid text-white text-xl fa-comments"></i>
            </div>
          </article>
          <article className="p-2 w-full sm:w-1/2 md:w-1/3 lg:w-1/4">
            <div className="card p-2 shadow bg-green-400">
              <h2 className='text-2xl text-white'>Expense</h2>
              <i className="fa-solid text-white text-xl fa-dollar-sign"></i>
            </div>
          </article>
          <article className="p-2 w-full sm:w-1/2 md:w-1/3 lg:w-1/4">
            <div className="card p-2 shadow bg-indigo-500">
              <h2 className='text-2xl text-white'>Places</h2>
              <i className="fa-solid text-white text-xl fa-location-dot"></i>
            </div>
          </article>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getStaticProps:GetServerSideProps = async (ctx) => {
  return {
    props:{
      visual:{}
    }
  }
}

export default Home
