import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Map: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Map</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Map Page</h2>
    </div>
  )
}

export default Map
