import { useState } from "react";
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Newsletter: NextPage = () => {
  const [state, setState] = useState(0);
  const [errorMsg, setErrorMsg] = useState("");
  // 0 - initial , 1 - loading, 2 - success, 2 - error
  //TODO: fix e data type
  const subscribe = async (e:any) => {
    e.preventDefault();

    setState(1);
    setErrorMsg("");
    console.log(e.target[0].value);
    try {
      const res = await fetch('/api/newsletter', {
        method: "POST",
        body: e.target[0].value,
      });

      const data = await res.json();
      if (data.error !== null) {
        throw data.error;
      }
      setState(2);
    } catch (e:any) {
      setErrorMsg(e.toString());
      setState(3);
    }
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Newsletter Signup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {state == 2 ? (
          <p className="font-medium mt-4 text-xl text-green-800">
              Thanks for subscribing, you will receive mail once we launch our
      website.
          </p>
        ) : (
            <form onSubmit={subscribe} className="flex flex-col mb-9 mt-4">
              <input required placeholder="Email address" type="email" />
              <button type="submit">Subscribe</button>
              {state === 3 ? (
                  <p className="text-red-500 mt-3">{errorMsg}</p>
                ) : (
                      ""
                    )}
              </form>
        )}
      </div>
    </div>
  )
}

export default Newsletter